### ISSUE TITLE
ci: fail if working tree is dirty

### ISSUE THREAD

**Issue by boneskull** [LavaMoat/lavamoat#721]
This should be a new step.  This can happen if e.g., a dependency is updated in `package.json` but `package-lock.json` didn't get updated.

**Comment by naugtur** [comment]
I'd be more specific - after the `npm ci` step it's possible that package-lock has changed - that'd be caused by versions from local package.json files being different than the noes preserved in package-lock. npm will not update the dependencies when `npm ci` runs, but it will fix/reformat the lockfile and update the version field at the top.

A test that's failing if package-lock was changed in CI would indicate "you forgot to refresh the lockfiles"

**Comment by boneskull** [comment]
IMO it should be if _any_ file under VCS changes. Cause that may affect a release regardless of what it is.
