### ISSUE TITLE
[Metamask] With scuttling disabled I see chrome.session.local but not chrome.session.session. Why?

### ISSUE THREAD

**Issue by tim-eucalyptus** [LavaMoat/lavamoat#736]
I'm trying to understand how LavaMoat works under the hood, so that I can eventually use this tool with my own extension application. Playing around with MM's source code and building a local version to test, I disabled scuttling in `index.js` via:

```
    // build lavamoat runtime file
    await lavapack.buildRuntime({
      scuttleGlobalThis: {
        enabled: false,
        scuttlerName: 'SCUTTLER',
        exceptions: scuttleGlobalThisExceptions,
      },
    });
```

I was expecting to be able to see `chrome.storage.local` AND `chrome.storage.session` via console log commands, but what I got was access to `chrome.storage.local` but NOT `chrome.storage.session`. Why is this? Is there a second layer of protection of `chrome.storage.session` that I'm missing? I looked everywhere possible I could think of in both MM and LavaMoats codebase and documentation.

Thanks in advance.

<img width="752" alt="CRX_metamask" src="https://github.com/LavaMoat/LavaMoat/assets/104312722/d253bdab-8410-4faf-a9d7-bd17d7defb1a">

**Comment by naugtur** [comment]
Scuttling as a feature is limited to top level globals or their own properties at most. It would not affect the depth of `a.b.c` AFAIK. 
And the error you get from scuttling is set up to tell you the field is not accessible due to scuttling.
Under scuttling, before you access either `session` or `local` you'd get:
```
Uncaught Error: LavaMoat - property "chrome" of globalThis is inaccessible under scuttling mode. To learn more visit https://github.com/LavaMoat/LavaMoat/pull/360.
  at Object.get (runtime-lavamoat.js:12078:17)
```

Could it be that the context in which you're running is not allowed access to session storage? Or maybe it's a default for one of the permissions MetaMask has in the manifest file?
